### ISSUE TITLE
Decoupling DID Core spec from LD-Proof / LDS specs

### ISSUE THREAD

**Issue by awoie** [w3c/did-core#154]
We should decouple the DID Core spec from LD-Proofs to allow people to use DIDs without understanding LD-Proofs. 

For example ...
- proof purposes are specified in the LD-Proof specification such as `assertionMethod`, `authentication` etc. We should always keep in mind that people want to use keys in DID Docs to generate proofs other than LD-Proofs as well, e.g., signing pdfs (probably not the best example). It feels a bit weird that someone needs to look at the LD-Proof spec to understand the different proof purposes. 
- allow other proofs for DID Documents, e.g., JWS.

**Comment by OR13** [comment]
I think this is actually a request to have the jsonld context documented, since that is what is required for both VC JWT and VC Linked Data Proofs.

**Comment by OR13** [comment]
Or rather, its not possible to use DID Docs for anything unless we understand what the properties mean, and in order to do that, we need to document every property in the existing jsonld context, as it applies to DIDs and VCs... and if we remove the context, then we would need to do the same thing with something else, like json schema, and ensure that they aligned or we would have a massively broken VC ecosystem...

**Comment by awoie** [comment]
@OR13 Thanks for the additional comments. That is what the intention was.

**Comment by OR13** [comment]
Related issues... in sidetree: https://github.com/decentralized-identity/sidetree/issues/362

**Comment by OR13** [comment]
Also related: 

- https://github.com/w3c/did-core/pull/156
- https://github.com/decentralized-identity/universal-resolver/issues/77

IMO the did core context should not rely on `"sec": "https://w3id.org/security#",`... since we cannot ensure that it is updated in a timely manner.

We might want to import the security context and its definitions into the did core spec... So that documentation can be fixed.

**Comment by OR13** [comment]
Blocked by registries discussion

**Comment by iherman** [comment]
See also discussions on https://www.w3.org/2020/03/16-did-minutes.html

**Comment by jonnycrunch** [comment]
This is also blocked as LD-Proofs are dependent on the RDF normalization algorithm which is draft and at least I am having inconsistent results.

**Comment by OR13** [comment]
@jonnycrunch does this help? 

https://github.com/rdf-ext/rdf-normalize
https://github.com/digitalbazaar/jsonld.js/#canonize-normalize
https://github.com/jsonld-java/jsonld-java

What language are you using?

**Comment by jonnycrunch** [comment]
Thanks.  I mostly use Go and Rust. 9 days ago https://github.com/piprate/json-gold (Go) was updated to use JSON-LD 1.1.  so, I still need to do some interop testing.

**Comment by msporny** [comment]
The direction that we're heading in here is decoupling the DID Core spec from the Linked Data Security specs.

**Comment by OR13** [comment]
I think this has been address by https://github.com/w3c/did-spec-registries/pull/47

**Comment by awoie** [comment]
I agree that this addresses my initial issue.

**Comment by jonnycrunch** [comment]
section 7.9 Proof states that the proof property, the value MUST be a valid JSON-LD proof.  I am having difficulty conforming to the spec with the CBOR representation with this constraint.  I will make a PR to update this section to address my concerns.

**Comment by OR13** [comment]
PRs to remove LD Proof stuff from core / registries welcome.

**Comment by msporny** [comment]
Still waiting on PRs.

**Comment by jonnycrunch** [comment]
will do

**Comment by brentzundel** [comment]
No comments since marked pending close, closing.
