### ISSUE TITLE
Underspecified semantics of revoked keys

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#168]
Section 6.3 on Public Keys https://w3c.github.io/did-core/#public-keys contains these statements about revoked keys in DID documents:
> The DID document MAY contain revoked keys. A DID document containing a revoked key MUST also contain or refer to the revocation information for the key (for example, a revocation list). Each DID method specification is expected to detail how revocation is performed and tracked.

This is so underspecified as to be an open invitation for non-interoperability.  If every method defines different syntax and semantics for public keys in DID documents, there's not much point of even talking about revoked keys in the specification.

The one actionable statement on revoked keys is this one, and I'm fine with it remaining:
> If a public key does not exist in the DID document, it MUST be assumed the key was revoked or is invalid.

**Comment by OR13** [comment]
Any did methods actually embedding revoked keys? I'm in favor of not allowing them in the document.

**Comment by jandrieu** [comment]
They address the use case of retaining keys that should still be considered valid for actions in the past, but are not current. As discussed in #14, keys that don't show up should be considered revoked (or never valid), but there are situations where retained keys could be useful.

**Comment by csuwildcat** [comment]
> They address the use case of retaining keys that should still be considered valid for actions in the past, but are not current. As discussed in #14, keys that don't show up should be considered revoked (or never valid), but there are situations where retained keys could be useful.

I sympathize with this desire, but why can't we serve this use case in a far more efficient, less spec encumbering manner via something like a cryptographically self-secured URI that listed/detailed any such keys and their past uses? (e.g. IPFS)

**Comment by jandrieu** [comment]
By that argument, why not just export all of the keys and include them by reference?

Seems to me the DID Document should include the relevant cryptographic material directly without requiring a separate dereference to a separate storage system.

**Comment by csuwildcat** [comment]
> By that argument, why not just export all of the keys and include them by reference?
> 
> Seems to me the DID Document should include the relevant cryptographic material directly without requiring a separate dereference to a separate storage system.

So DID Methods should be thought of a long-held data storage system? <-- this is specifically what just about any robustly decentralized DID Method implementation that proceeds beyond small batch cottage use will never be able to support (if they are trying to keep their systems as trustless as possible). My prediction is that the net effect of encouraging DID Doc bloat will push people toward things like `did:web`, because they will see it as a feature that they can drop megabytes of data into a DID Doc and do it 'for free'.

In the end, these are game theoretical economic systems, and if we're not careful with balancing the very real concerns, limitations, and scale issues, I genuinely believe we will see centralized 'Decentralized' Identifiers gain even more traction against actual DIDs.

**Comment by jandrieu** [comment]
Hmmm... I'm of two minds on this. 

First, when the controller has a business requirement to publish old-but-still-valid keys, it has to be stored somewhere and the role of the DID Method is to return the current authoritative DID Document.

So, from that angle, the DID Method must either store or link to a reliable store that can produce the authoritative DID Document. That is, yes, it is a long term store.

FWIW, BTCR uses a mechanism called "extension documents" that build out additional DID Document elements. There are ongoing discussions about whether or not that is the right approach.

On the other hand, I'd argue only the current crypto should be listed. Period. No service endpoints. No verification methods. Those values can be found using a directory if you so choose to publish them or passed in a capability signed by the root proof mechanism. 

So, yes, I agree. Let's get the bloat out of the DID Document. 

I'd prefer to start with service endpoints, since they create such a nightmare wrt matrix parameters. 

Given that "revoked keys" is a relatively straightforward property to put in a DID Document--it has no impact on the DID syntax and can be completely contained in the Document--it introduces far less complexity. And it *is* presenting crypto that is valid for certain interactions. Although, I think "revoked" is under specified without some sort of explanation about why they are revoked. @ChristopherA would like to label a key as compromised, while @ken-ebert's use case needs some sort of timeframe of limited validity.

My current thinking is that if we are willing to be aggressive about trimming down the DID Document, the *right* way to handle the use cases @ChristopherA and @ken-ebert want is to run a certificate transparency log (conceptually) that records state changes in keys. Such a service need not be in the DID Document. People just need to know that such logs are available and they can go query one, just like any directory. The DID is a unique identifier perfectly suited for looking up such data in a directory.

**Comment by msporny** [comment]
> there are situations where retained keys could be useful.

Sure, and they're academic and no one has needed to do this to this point. I suggest we stay silent on the topic in the spec, which is a valid spec approach, it until it becomes clear that it's needed.

**Comment by jandrieu** [comment]
@msporny You're dismissing multiple use cases presented by members of the group. 

I'm not saying we add revoked keys at this point because we don't have that proposal on the table. 

The simplest solution is to simply not mandate whether or not revoked keys can go in the document. When someone can propose a reasonable use case and a specific mechanism for doing so, we can debate that.

But right now, there is no consensus on language stating that revoked keys MUST NOT be listed in the document.

**Comment by msporny** [comment]
> @msporny You're dismissing multiple use cases presented by members of the group.

I know that folks have suggested use cases in the past, and I've spoken with some of them about addressing their use case... but I don't know of any remaining that aren't solved by 1) using a DLT, or 2) acknowledging that the DID Method can't be audited (and thus can't do historical queries).

> The simplest solution is to simply not mandate whether or not revoked keys can go in the document.

The simplest (and most secure) solution is to be crystal clear that placing revoked keys in a DID Document is a bad security practice.

Do we have the use cases for revoked keys written anywhere? That should probably be the first step, documenting these revoked keys use cases so we can analyze how they might be solved without opening up the security attack surface for DID Documents.

**Comment by jandrieu** [comment]
One of the tensions here is that some of the approaches for doing what you ask for were incorrectly believe to be addressable via matrix parameters. I believe the same mistake would apply if you rely on the historicity of a DLT. 

Unless you can specifically say that a key was revoked for a particular reason, you cannot assume that a key that has been revoked was valid at any particular time because it may have been compromised from the get-go. Using a time-based query to a resolver cannot tell you if the key was actually valid at a particular date, because the very reason it was revoked may be that it had been compromised for some time.

Requests for those use cases have been made. PRs accepted at https://github.com/w3c/did-use-cases/

**Comment by msporny** [comment]
> I believe the same mistake would apply if you rely on the historicity of a DLT.

Well, one thing is crystal clear at this point -- we don't have consensus.  :P

So, we should pull back the PR and continue discussion here. My expectation is that this thread is going to turn into a special topic call since we have use cases we're going to have to discuss. I forgot about the BTCR one -- that's the one I find most compelling as did:web has a similar use case. I'm concerned that we're trying to protect against a faint edge case, but that's what we should continue to explore in this issue and a potential future special topic call.

**Comment by msporny** [comment]
@jandrieu we need you to review PR #279 ASAP. If you do not engage, we will merge the PR above.
