### ISSUE TITLE
Do we really want to recommend polling for changes?

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#179]
Section 10.5 Notification of DID Document Changes https://w3c.github.io/did-core/#notification-of-did-document-changes contains:
> Self-monitoring. A DID subject can employ their own local or online agent to periodically monitor for changes to a DID document.

Do we really want to recommend polling for changes?  That hardly seems like a reliable or scalable practice for constructing systems using or implementing DIDs!

**Comment by OR13** [comment]
This is akin to subscribing for updates regarding the use of your SSN... if you don't know who is using your SSN, you don't know that someone else is using it....

**Comment by selfissued** [comment]
Can whoever wrote this text speak up and say why this text is even there?

**Comment by dlongley** [comment]
Note that the section right above this one (listed first) says this:

```
Subscriptions. If the DID registry on which the DID is registered directly supports change notifications, this service can be offered to DID controllers. Notifications could be sent directly to the relevant service endpoints listed in an existing DID.
```

**Comment by selfissued** [comment]
I will review this and probably create a PR removing the suggestion for polling.   That way we'll see if there's actually support for this and why.

**Comment by kdenhartog** [comment]
I think a subscription service that sits over the top of a DID registry would be the more efficient way of handling this and would be in favor of removing the suggestion to use polling. I think it's suffice to say if polling __really__ is the only way to discover an update, it's likely the obvious answer.

**Comment by rhiaro** [comment]
I don't think the wording is harmful because of the preceding text (noted in https://github.com/w3c/did-core/issues/179#issuecomment-600140403). It's also non-normative. 

I don't think the wording is necessary because it's not like developers needed to be reminded of the existence of polling as an option. It's not like it's a very DID-specific or totally out-there solution. If someone wants to poll, they will think of it themselves without the spec's help. 

In the interests of just giving people less to read overall, I'm +1 to removing it.
