### ISSUE TITLE
[DID Operations] "all the operations required of a CKMS" are not specified on the body of this section

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#21]
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/147)

**Comment by rhiaro** [comment]
The text this issue was originally opened for now reads:

> These operations can effectively be used to perform all the operations required of a CKMS (cryptographic key management system). For example, key registration, key replacement, key rotation, key recovery, and key expiration. 

I think this makes the CKMS operations in relation to DID operations sound less literal and more indicative; each CKMS operation is covered by one of the DID operations (ie. registration and recovery by Read, replacement and rotation by Update, expiration by Deactivate). If agreed, this issue can be closed with no further spec text changes.

**Comment by msporny** [comment]
This issue will be closed soon unless there is an objection to the changes made to address the issue.

**Comment by msporny** [comment]
The document has been modified based on input from the issue commenter. No further changes have been requested. Closing.
