### ISSUE TITLE
Shall we need more words on how DIDs support for a centralized identity systems?

### ISSUE THREAD

**Issue by YueJing95** [w3c/did-core#211]
From the v1.0 introduction section, “DID methods can also be developed for identifiers registered in federated or centralized identity management systems. Indeed, **all types of identifier systems can add support for DIDs.** This creates an interoperability bridge between the worlds of centralized, federated, and decentralized identifiers.”

DIDs are supposed to interoperate with current **centralized identifiers**. Does this mean that, for example, a GTIN13 barcode from GS1 can add to method-specific parts of a DID, without changing the actual encoding structure? 

By doing this, DIDs can combine any kinds of identifiers in a centralized management system, just using  DID : DID method : current identifier

**Comment by iherman** [comment]
Actually... I am not sure I understand what this statement really means. Can one of the editors give an example?

**Comment by YueJing95** [comment]
@iherman Sorry for misleading, I mean some fictional DIDs like:

did : fiction :  07350053850019
did : fiction : 0000-0003-0782-2704

They both are new DID identifiers with the DID method called "**fiction:**", but the method-specific parts, which are "07350053850019" and "0000-0003-0782-2704", are original identifiers in other centralized systems. Is this possible?

**Comment by iherman** [comment]
That is entirely possible by defining the `fiction` method accordingly.

Actually, if we want to collect all those identifiers under the same hood, the following would make a better structure:

```
did:fiction:gs1:07350053850019
did:fiction:orchid:0000-0003-0782-2704
```

but, again, this is the decision of the authors of the `fiction` method.

**Comment by peacekeeper** [comment]
@YueJing95 this is a great question! It has come up a few times before.. The answer is a bit complicated. On one hand, it is possible to define a technically compliant [DID scheme](https://w3c.github.io/did-core/#dfn-did-schemes) and [DID method](https://w3c.github.io/did-core/#dfn-did-methods) based on centralized identifiers, however this would not be fully in line with the abstract concept of a "Decentralized Identifier (DID)". See for example the following spec text:

- _The `method-specific-id` value MUST be able to be generated without the use of a centralized registry service._
- _DIDs achieve global uniqueness without the need for a central registration authority._
- _These new identifiers are designed to enable the controller of a DID to prove control over it and to be implemented independently of any centralized registry._

The challenge is to define what "(de-)centralized" means. This is why the Working Group will publish a "Rubric for Decentralization of DID Methods" to evaluate DID methods. This work is led by @jandrieu  (current draft [here](https://docs.google.com/document/d/1rYdWiwawWmLOWtHRvT0GzYcdewW_OS9M2mAkENLFdtY/)).

There has been some work on a [`did:web`](https://github.com/w3c-ccg/did-method-web) method (an approved Work Item of the Credentials Community Group) method as well as a [`did:facebook`](https://github.com/peacekeeper/did-method-facebook/blob/master/did-method-facebook.md) (as a thought experiment, not serious).

**Comment by philarcher** [comment]
This discussion is obviously of more than passing interest to me and my GS1 colleagues. We have been considering whether we might indeed define a GS1 method and something like
`did:gs1:gtin:5050765177542` would be a candidate (we'd need to insert `gtin` or `01` before the actual GTIN as we have other identifiers besides GTINs).

But let's look at the list that @peacekeeper (rightly) quoted.

> * _The `method-specific-id` value MUST be able to be generated without the use of a centralized registry service._

That rules us out. The GS1 system is the very epitome of a centralised system, however federated we may be.

> * _DIDs achieve global uniqueness without the need for a central registration authority._

We fail here too.

Like all ID schemes, we have a central controlling authority (GS1 Global Office) that hands out [prefixes](https://en.wikipedia.org/wiki/List_of_GS1_country_codes) and then our member organisations around the world go from there (there are 114 GS1s around the world, plus Global Office)

> * _These new identifiers are designed to enable the controller of a DID to prove control over it and to be implemented independently of any centralized registry._

Well, we might get close to this. I don't know what `5050765177542` identifies but I *do* know that it is licensed by Nexus Industries in Ashford, UK. That's because it's structured to include the GS1 member who issued it (GS1 UK) and then more digits tell you the licensee. So `5050765` is what we call a Global Company Prefix. 

Our current thinking is that we might (in future) issue a verifiable credential that Nexus Industries can use to prove that they are the GCP licensee. If it were possible to prove control of  `did:gs1:gtin:5050765177542` directly, rather than as a VC, then there *might* be some mileage in that for us for sure.

To come back to @YueJing95's original question - we looked at the DID spec and, for the reasons given, quickly decided that, actually, no, you can't use a DID with a centralised ID, despite the claim to the contrary. VCs? Yes, DIDs? No. So I agree - some clarification wold be very welcome.

**Comment by kdenhartog** [comment]
While I get the sentiment of your points @philarcher, I'd argue that because point one is the only normative statement, you could make a centralized did method. The idea I've thought about for this is to do something like a pgp server where the did identifier is the genesis public key when published to the server. This would address the normative statement in point 1 from @peacekeeper.

Technically, the identifier didn't rely on the pgp server to be created, so I think you could stretch it to say point 2 is met.

Finally, since the public key is used to control the identifier, I think this qualifies for point 3.

In reality, a pgp server is kind of similar to our use of blockchains if you squint at it right. And if the PGP server happened to have redundant nodes with a bit of consensus, well that's about the same as some ledgers available today.
