### ISSUE TITLE
Clear explanation on how can A DID have more than one controller

### ISSUE THREAD

**Issue by YueJing95** [w3c/did-core#260]
The **DID controller** is defined as `The entity that has the ability to make changes to a DID document. A DID can have more than one controller. `

Based on the discussion of  previous issues, there are two cases for the relationship between **DID controller** and **DID subject**:
Case one, **the controller is the subject**, for example, people(controller) can create a VC(subject) for themselves to prove the ID information.
Case two, **the controller is not the subject**, for example, people(controller) might give their pets(subject) or properties a DID.

For case one, which the controller is the subject, how can a subject have more than one controller? In another word, how can a couple of people controller only VC which is supposed for the only one person?

For case two, which the controller is **not** the subject, is that rational that a brunch of people can control one subject, which is not belonging to a specific person? Especially for the IoT cases, where people give things DIDs, and the ownership of the things might be changed. Is IoT case a reasonable explanation for `A DID can have more than one controller.`?

**Comment by kdenhartog** [comment]
> For case one, which the controller is the subject, how can a subject have more than one controller? In another word, how can a couple of people controller only VC which is supposed for the only one person?

This is most common when the same subject has multiple devices. For example, my DID has did#key1 for my mobile device and did#key2 for my laptop. In this case, I possess both devices, they both represent me, and they both have control over the did (assuming verification methods are true).

> For case two, which the controller is not the subject, is that rational that a brunch of people can control one subject, which is not belonging to a specific person? Especially for the IoT cases, where people give things DIDs, and the ownership of the things might be changed. Is IoT case a reasonable explanation for A DID can have more than one controller.?

Yes, this is a good example. Another one that I like to think about is in the case where an enterprise has multiple sysadmins who have the "keys to the kingdom". In this case, the company is the subject of the did, but the multiple sys admins are the ones who actually take actions on behalf of the corporation such as rotating keys and updating endpoints.

**Comment by jandrieu** [comment]
Related to the latest comments in https://github.com/w3c/did-core/issues/269

**Comment by talltree** [comment]
I propose to add an Appendix (all non-normative text) called "What Does a DID Identify?" that will include diagrams to explain the relationship between DID controllers, DID subjects, and DID documents. It will be relatively short, but this combination of text and diagrams should answer a whole lot of questions that spec readers may have about these three crucial concepts.

This Appendix will also illustrate the concept of multiple DID controllers. However it will not discuss the security implications of that. Rather it should reference that subheading in the Security Considerations section.

@iherman has volunteered to be a sounding board for this Appendix.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-03-11-did-topic#section2) on 2021-03-11

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-03-11-did-topic#resolution1):  Allow [did:3](did:3) to be registered in the DID Spec Registries -- pull in PR 260.***

<details><summary><i>View the transcript</i></summary>

### 2. registration of did:3 method 

_See github issue [#260](https://github.com/w3c/did-core/issues/260)._




**Manu Sporny:** the DID Core spec allows this (single-char DID methods).  
… there is mention about being concerned about this kind of stuff  
… their response is they shipped it; it needs to be in  
… are we going to restrict methods to be at least 2? characters?  

**Brent Zundel:** Topic 1: possible constraints on DID method length  

**Ivan Herman:** not that i like this [did:3,](did:3,) but do we want to get into a normative change in the core spec, and reissue a CR? (not published yet, but right after)  
… this is a normative change in the core spec. it allows to have one-character method name.  

> *Brent Zundel:* +1 to needing to change core spec in order to say no here

**Markus Sabadello:** i don't think anyone is suggesting a change to the DID Core spec to change the normative syntax of what is allowed or not. but there is a difference of what is allowed in the syntax and what is the policy on what is allowed in method names  

> *Orie Steele:* There MIGHT be a difference, if the registry refused to accept conformant DIDs...

**Markus Sabadello:** it could be to not change core spec, their did method would continue to function and be compliant, but doesn't mean it has to be accepted and listed in the registries  

> *Drummond Reed:* +1 to Markus's point

**Markus Sabadello:** registries meant to help with interoperability, discoverability, etc., but no hard requirement to use it.  

**Manu Sporny:** agreeing with markus. might be talking about a process change to the registries process. strongly advise to use more than one character. registry may/will not list methods with single-characters. but grandfather in [did:3.](did:3.) proposal to modify process  

**Brent Zundel:** have to get [did:z](did:z) written fast  

**Drummond Reed:** speaking from direct experience in another namespace. what we saw: single-char methods splattered on fast.  
… we strongly rued the fact that we had not set that policy. i was dismayed to find out about [did:3](did:3)  

> *Amy Guy:* it does take quite a lot of work to squat a did method

**Drummond Reed:** just the fact that is out there - i would like to see documentation that it was/is actually in use  
… could see that if they provide strong enough evidence, we could allow it  
… strongly feel we should set the policy. interestingly enough, ivan, i wasn't even thinking of changing the ABNF. since it would strictly be a registry policy.  

> *Amy Guy:* +1 TallTed

**Ted Thibodeau Jr.:** i don't think we want to discourage people from registering their methods, because that will just encourage collision. it will be easy for other people to do another [did:3,](did:3,) and then how do they resolve.  

> *Amy Guy:* which is worse? squatting or collisions?

> *Orie Steele:* strong agreement

**Ted Thibodeau Jr.:** there are just too many problems that arise here. we want every did method to be registered. unfortunately, we can't care whether they have single char.  

> *Drummond Reed:* I strongly disagree with Ted on this point.

**Ted Thibodeau Jr.:** to ensure the integrity of the system. discouraged to hear otherwise  

**Jonathan Holt:** don't see why it matters, one char, two, chars. don't think is policy needing to be enforced  

**Manu Sporny:** sounds like we are a bit split on this and maybe shouldn't tie up a bunch of time talking about. have more important things to discuss. i can't think of a proposal at this point that would pass.  

> **Proposed resolution: accept any attempt to register a conformant method on a first come first serve basis** *(Orie Steele)*

**Manu Sporny:** seeing objection to limiting it. i think everyone agrees we want people to register their methods.  
… sounds like we should convince people to register their methods  

**Orie Steele:** this ship sailed when we allowed DID Methods to be one character long and be valid. if not changing in core spec, i can't see attempt to block registering conformant did methods on a first-come first-serve basis. either create tremendous bias or allow existing methods to forever have higher ground. [did:3](did:3) only single-char method: terrible. same for 2-char or other limits. strongly  

> *Charles Lehner:* object to blocking registration of methods conforming.

**Orie Steele:** must allow them. there will be a mad dash. welcome to managing a namespace.  

> *Orie Steele:* why discourage a thing that literally everyone will want... everyone wants short names....

**Markus Sabadello:** like manu's idea to allow this one, not prohibiting, but make a strong warning discouraging them  
… regarding opinion must use registry to avoid collision: not how it sohuld be. we should not consider the registry something that must be used. in charter, DID implementations must work without relying on a single registry  
… registry is utility making certain things easier, but DIDs, DID resolution and the ecosystem must also function if you don't use the registry.  

**Brent Zundel:** could we work it into the reg process to require evidence that they are not just name-squatting?  

> *Amy Guy:* what brent said is already in the process isn't it? I thought they needed to be fully spec'd at least

**Brent Zundel:** +1 to running Orie's proposal  

**Drummond Reed:** will wait until after proposal  

**Brent Zundel:** anyone want to suggest modifications to proposal before formally running it?  

> *Amy Guy:* +1 drummond... there are other things about trademarks, offensive language, etc aren't there

**Drummond Reed:** maybe now reading it i'll reverse myself. maybe should have rest of call about what are going to be the policies to follow here. first come first serve: very basic, makes sense. but if don't look at in conjunction with rest of policies to apply. assuming Orie's not talking about everything going in, should look at other policies to apply.  
… almost feels dangerous to start there. really need to look at the full body of policies  

> *Manu Sporny:* [https://w3c.github.io/did-spec-registries/#the-registration-process](https://w3c.github.io/did-spec-registries/#the-registration-process)

**Drummond Reed:** need to discuss not just each one individually, but all together. as said, welcome to managing a NS.  
… like the president of IBM saying would not be more than 3 computers. i thought there wouldn't be more than a dozen DID methods  

> **Proposed resolution: accept any attempt to register a conformant method on a first come first serve basis** *(Brent Zundel)*

> *Orie Steele:* +1

> *Manu Sporny:* +0.6

> *Drummond Reed:* -1

> *Ivan Herman:* 0.9

> *Jonathan Holt:* 0

> *Brent Zundel:* 0

> *Drummond Reed:* the reason being that it's not specific enough yet

> *Ted Thibodeau Jr.:* +0.75 I think we're rather painted into a corner

> *Amy Guy:* -1 without caveat about other registration policies also being met

> *Manu Sporny:* cel: abstain

> *Markus Sabadello:* 0 we have that already, we need to talk about policies, not order

**Brent Zundel:** we have underwhelming support plus a couple -1s.  

**Manu Sporny:** remind everyone we have a [process](https://w3c.github.io/did-spec-registries/#the-registration-process). it has been edited a number of times. that is the process, you have to do all those things. a number of MUSTs and MUST NOTs  

> *Amy Guy:* +1 if meeting the rest of the process is implicit

> *Amy Guy:* +1 then

**Manu Sporny:** only thing we are talking about is that you must... difficult to find wording for this, want to abandon and more on. supposed to be a softball one while waited for Orie to join. sounds like people feel strongly about this. let's come back to it later  
… i don't think there is any real way we can stop. let's look at immediate decision: are we going to stop [did:3](did:3) from being registered? i don't think so. there is proof they have been using it. i don't think we can stop it. suggestion is to let PR 260 to go through, as no variation would prevent them to be registered  

> *Drummond Reed:* but they did not register it with the then-registry, correct?

**Manu Sporny:** can come back to do we want a policy to restrict this stuff  
… proposal to allow PR 260, [did:3](did:3) to be registered  

**Brent Zundel:** if anyone would like to speak out in opposition, add to q  

> *Orie Steele:* or block it

**Ivan Herman:** going a bit further, i don't think there is any reason why we would not register that one. but once we do that, we have created a precedent. no real reason to allow this one and not something else. sort of too late. should forget about this question altogether  
… There may be some other discussions about the registration policy more generally, probably more important ones.  

> *Orie Steele:* +1 to ivan... there is no way to kick this can

**Ted Thibodeau Jr.:** there was some statement that because DIDs should not be reliant on any central registry, there should not be reliance on this registry. i think registering methods is different from registering DIDs per-se.  
… part of the point of registering the method is so that people [...] can figure out which one satisfies their needs.  

> *Markus Sabadello:* [https://www.w3.org/2019/09/did-wg-charter.html](https://www.w3.org/2019/09/did-wg-charter.html) - "These new identifiers are designed to enable the controller of a DID to prove control over it and to be implemented independently of any centralized registry, ..."

> *Drummond Reed:* I'm afraid that is true - and sad - but I will point out that the [did:3](did:3) people did not actually register with the then-registry...

**Ted Thibodeau Jr.:** not the same as reliance on a centralized registry that we try to prevent.  

> **Proposed resolution: Allow [did:3](did:3) to be registered in the DID Spec Registries -- pull in PR 260.** *(Manu Sporny)*

> *Orie Steele:* +1

**Brent Zundel:** manu dropped draft proposal  

> *Amy Guy:* +1

> *Manu Sporny:* +1

> *Brent Zundel:* +1

> *Ivan Herman:* +1

> *Jonathan Holt:* +1

> *Markus Sabadello:* +0.5

> *Drummond Reed:* 0

> *Ted Thibodeau Jr.:* +1

> *Charles Lehner:* 0

> ***Resolution #1: Allow [did:3](did:3) to be registered in the DID Spec Registries -- pull in PR 260.***

</details>
