### ISSUE TITLE
The DID context document is now 404

### ISSUE THREAD

**Issue by troyronda** [w3c/did-core#290]
The DID context document in the specification no longer resolves:
https://www.w3.org/ns/did/v1

**Comment by kdenhartog** [comment]
probably broke the redirects when the did-core-registries repo was renamed. I believe the context is built from there.

**Comment by kdenhartog** [comment]
@iherman are you the only one who can update those redirects or can @msporny or @OR13 also do it?

**Comment by iherman** [comment]
> @iherman are you the only one who can update those redirects or can @msporny or @OR13 also do it?

nop, only I can do it (or, to be more exact, only W3C staff can do it). I have done it, my apologies not have thought of this before.

That being said: I was a bit surprised. github is good at redirecting the repo pages, ie, `https://github.com/w3c/did-core-registries/` is still working (and will stay so) because it is redirected to the new one. This means all the clones on our machines work with the git commands. I expected the same will happen with the corresponding `github.io` URL-s, and this does not seem to be the case... One learns something every day!

Issue solved, closing...
