### ISSUE TITLE
Remove `proof`

### ISSUE THREAD

**Issue by rhiaro** [w3c/did-core#293]
`proof` should not be in DID Core as it is a way to protect content not used by all DID methods. Propose removing it altogether, understanding that it will still be available for those that want to use it via the DID Spec Registries.

**Comment by peacekeeper** [comment]
This has been proposed before in https://github.com/w3c/did-core/pull/26, but I think our understanding of it has evolved since then.

It has been suggested that proofs are not data about the subject, but rather 1) metadata about the DID document, and/or 2) metadata about resolution (see https://github.com/w3c/did-core/issues/65#issuecomment-597030882). This would support that `proof` should be removed from the DID document and possibly from DID Core altogether.

**Comment by kdenhartog** [comment]
> It has been suggested that proofs are not data about the subject, but rather 1) metadata about the DID document, and/or 2) metadata about resolution (see [#65 (comment)](https://github.com/w3c/did-core/issues/65#issuecomment-597030882)). This would support that `proof` should be removed from the DID document and possibly from DID Core altogether.

+1 to the sentiment expressed here

**Comment by marceljay** [comment]
I think it needs to be discussed what the DID-Core spec should address, as it describes important concepts that go beyond the key components of DID documents. It is stated in [7.9 Proof](https://www.w3.org/TR/did-core/#proof) that such proofs are optional, since these proofs can be implicit (e.g. did:sov) and thus considered metadata.   

I would suggest a revison of the whole chapter 7, which has some confusing parts, for example  regarding [verification relationships](https://github.com/w3c/did-core/issues/193). 
As  a suggestion, the chapter could be split into a first section stating the required properties of a DID doc, and a second one that explains parts of the DID document that are optional. 

My suggestions in short:
- Describe implicit proofs in 7.9 and that proofs can be considered metadata
- Revise chapter 7 and make it more comprehensive and complete (and give it a less ambiguous title than "Core Properties")
- Consider migrating the DID document part to its own spec that is filled with detailed explanations and more examples
