### ISSUE TITLE
Verifiable credential creation flow implementation

### ISSUE THREAD

**Issue by mehranshakeri** [w3c/did-core#366]
In [section 6.1 of VC use cases](https://www.w3.org/TR/vc-use-cases/#how-a-verifiable-credential-might-be-created) and afterwards in 6.2 for usage of VCs, no write transaction to a [registry](https://www.w3.org/TR/did-core/#dfn-verifiable-data-registry) is required.

Based on my understanding, only when the issuer needs to revoke a VC, there should be a transaction to the registry revoking that credential.

Some implementations write the hash of the VC on the registry and later on they can revoke the VC with revoking the hash. This means there will be one write transaction per issued VC to the registry. Assuming our registry is a public blockchain, this will be costly and a slow step.

For sake of simplicity, let's assume the proof on a VC is a simple digital signature using public/private key pairs. Also the issuer has a master key pair (MK) where its public key is known to everyone (at least to holders and verifiers). Could the following flow be a secure VC issuance and revoke process?

1. Issuer generates a new pair of keys (K1)
2. Issuer signs the **PK1** (the public key of **K1**) using master key **MK** to prove origin of **K1** and delivers the signed **PK1** to the holder
3. Issuer signs the VC using **K1** and delivers it to the holder (steps 2. & 3. could be done in one step)
4. Any verifier trusting the issuer can verify the VC by tracing back the signatures to the known public key of issuer's master key
5. To revoke the credential, the issuer must send a transaction signed with its master key **MK** to the registry (public blockchain) calling revoke on the **PK1**. This means as part of verification process, verifier must read the registry for any revoke transaction from **MK** on **PK1**

This flow ensures minimum number of transactions to the registry which is only in time of revoke events. (Of course, if the VC has an expiration date and it reaches before revoke event, no revoke transaction is necessary)

I couldn't find any documentation or implementation for this flow but I assume I'm not the first one coming up with it :). If this already exists, I really appreciate it if you could redirect me to it, otherwise I would like to know if there is any security concerns to this flow and that's why it's not mentioned anywhere or it's just new?

Thank you in advance.

ps: I've created the same issue in [use-case repo](https://github.com/w3c/vc-use-cases/issues/121) but it seems nobody has checked that repo for last year

**Comment by peacekeeper** [comment]
Hello @mehranshakeri this is an interesting question.. Both revocation and credential issuance flows are areas where a lot of discussion and innovation is happening. However, this is the wrong place to raise this, since this repository is about the DID Core specification. Unless I am missing anything, I don't think your use case and issuance flow is directly relevant to the scope of the DID Core specification.

Here are some suggestions where you could discuss this:

1. The other place where you created this issue (vc-use-cases) definitely makes more sense.
2. You could ask on the W3C CCG mailing list: https://www.w3.org/community/credentials/
3. You could check the resources at the Claims and Credentials Working Group in DIF, and ask your questions there: https://identity.foundation/working-groups/claims-credentials.html

Hope this helps. If this makes sense, please close the issue here.

**Comment by mehranshakeri** [comment]
Thank you @peacekeeper I will follow up with other two channels :)
