### ISSUE TITLE
constraints on assertionMethod? Or a different verification purpose?

### ISSUE THREAD

**Issue by dhh1128** [w3c/did-core#375]
I *think* (could be wrong) I would like to be able to declare a block inside `assertionMethod` that contains constraints -- essentially, I want to be able to say, "This DID or key can make assertions on behalf of this DID, but with the following restrictions: ___" The restrictions could be schema-based ("only if the assertions conform to one of these schemas"), and/or time-based ("between July 1 at 6 am and July 1 at noon, while I'm in surgery"), and/or VC-based ("as long as they can present an unrevoked credential demonstrating X").

My main use case is delegated issuance. I want company A to be able to say in its DID doc: "We delegate the issuance of our employment credentials to company B." But Company B shouldn't get the ability to make unrestricted assertions on behalf of A -- only to make assertions with carefully crafted constraints. You can see from my time-based example that it also has applications in personal use cases, but that's not my main focus.

I am aware that this authority could be conferred in other ways, but I am fretting at the limitations:

* A could give B a capability. But per @jandrieu , capabilities have to be evaluated by their creator (or at least within an ecosystem that the creator controls). That wouldn't seem to apply in this case. Besides, capability invocation is a different verification purpose; I'm not sure making one such purpose depend on another has the correct security outcome.
* A could give B a VC conferring this authority. That fits better (and indeed, is the very mechanism I discussed in the [chained credential concept I've proposed for all VC ecosystems](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0104-chained-credentials/README.md)). However, I don't know of a way of making that sort of delegation discoverable. I want the discoverability to obtain, starting from A's DID doc.
* A could create a special-purpose DID where the DID subject is A's employment credentials, and make B the controller of it. The problem is that A cedes too much control to B. I want A to have a ripcord where it can yank back the delegation it made to B.

To avoid cluttering a DID doc too much, the simplest form of constraint I can imagine is one where A's `assertionMethod` block says something like this:

```jsonc
"assertionMethod": [
    {
      // Allow B's DID (did:...fghi) to make assertions for (this) A's DID
      "id": "did:example:123456789abcdefghi",
      "constraints": {
          // Find out what constraints apply by demanding that B give you
          // a presentation in DIF presentation def format, as documented
          // at the following URI. This implies that A has issued to B a VC
          // capable of satisfying the presentation def. That VC would have
          // fields disclosing whatever constraints apply.
          "presentation_def": "https://a.com/empl-cred-deleg.json"
      }
    }
  ],
``` 

Perhaps there are better ways to do this, that don't complicate `assertionMethod` as this does. I'm open to other thinking. But you can see how this makes the delegation discoverable, and it gives A a ripcord that B can't override or hide, whereby the delegation can be cancelled. (VC revocation could do that, too -- but B could play games with the revocation latency that are less likely to be possible if A's DID is resolved. You could even put a TTL in the `constraints` block to make explicit the latency limits that A considers safe.)

**Comment by dhh1128** [comment]
Pinging @dlongley and @OR13 and @peacekeeper , as I think they might have opinions about this. Dave, does this do too much violence to the simplicity you were hoping to achieve with verification purpose sections of a DID doc corresponding to simple RDF triples? If so, what alternative do you like best?

**Comment by OR13** [comment]
You can certainly create an extension which defines "verification method constraints"... and suites that MUST care above them....I would worry about what happens when the properties are ignored, as they w

I would personally rather not see this in a verification method... I would prefer to discover this information via a service endpoint... or see it displayed in a serviceEndpoint object defintion.

**Comment by dhh1128** [comment]
@OR13 : I'm not surprised that my suggestion feels odd -- but I *am* surprised by the counter suggestion. How would this have anything to do with a service? Are you saying that the delegator should run a service where the world can talk to it to discover what it's delegated?

**Comment by tplooker** [comment]
This is territory I've always felt gets murky w.r.t did documents. The impression I have always had is that there needs to be support for a core set of authoritative statements in a did document that delegates some aspects of authority (e.g what we have now), however how rich and granular this should get w.r.t its definition in did-core is still blurry to me. I agree with @OR13 that catering for this via an extension is perhaps the easiest way and that other valid ways to cater for this delegation would be via a service.

**Comment by dlongley** [comment]
> I think (could be wrong) I would like to be able to declare a block inside assertionMethod that contains constraints -- essentially, I want to be able to say, "This DID or key can make assertions on behalf of this DID, but with the following restrictions: ___" The restrictions could be schema-based ("only if the assertions conform to one of these schemas"), and/or time-based ("between July 1 at 6 am and July 1 at noon, while I'm in surgery"), and/or VC-based ("as long as they can present an unrevoked credential demonstrating X").

So, you can create a verification method that expresses whatever constraints in it you'd like. However, this sort of information sounds like it belongs somewhere other than a DID Document. Ideally, it would be expressed somewhere that comes into contact with the system that performs the signing vs. the one that performs the verifying. Verification relationships help verifiers prevent proofs that have already been created from being misused for something other than their intended purpose. Here, it appears that you want to place specific restrictions on what you can actually sign -- and stop the proof from being created in the first place.

I would also shy away from these sorts of specifics in a DID Document just because of their tendency to reveal more information about a DID subject than may be desired. Some DID methods may be more naturally privacy preserving than others, but verification methods are meant to be DID method agnostic -- which may lead some to attempt to use them with DID methods where they may be harmful. Ideally, DID method designers will place their own restrictions to help prevent that sort of thing, but in the interest of avoiding such issues, my advice would be to put this sort of information elsewhere both for privacy purposes and because it seems to be related more to the specific message that is being signed than the general intent of a proof.

> My main use case is delegated issuance. I want company A to be able to say in its DID doc: "We delegate the issuance of our employment credentials to company B." But Company B shouldn't get the ability to make unrestricted assertions on behalf of A -- only to make assertions with carefully crafted constraints. You can see from my time-based example that it also has applications in personal use cases, but that's not my main focus.
> 
> I am aware that this authority could be conferred in other ways, but I am fretting at the limitations:
> 
> A could give B a capability. But per @jandrieu , capabilities have to be evaluated by their creator (or at least within an ecosystem that the creator controls). That wouldn't seem to apply in this case. Besides, capability invocation is a different verification purpose; I'm not sure making one such purpose depend on another has the correct security outcome.

I actually think this applies quite nicely (and I have used capabilities for almost exactly the same use case myself). If A exposes an endpoint for performing digital signatures (e.g., using WebKMS), it can give B a capability to use that endpoint. The capability itself can carry whatever application-specific restrictions are desired -- or -- the endpoint can be made so it specifically bakes in those restrictions such that whoever has a capability to use it gets the same restrictions. Either approach works and keeps these restrictions between the two parties vs. having it leak out elsewhere.

In this scenario, B will be using a key to take an action ("invoke a capability") -- to *use* the signing endpoint. Their key material is not used directly in the assertion itself. So, B would be using a key (for `capabilityInvocation`) to invoke the capability that enables them to use the signing endpoint -- and A would still be using a key (for `assertionMethod`) to sign the assertion (from behind the endpoint). The assertion (e.g., VC) would be signed with A's key.

**Comment by agropper** [comment]
I worry that I can't follow any of this and I really think I should try
because there are privacy and adoption implications.

This is a delegation use case. A does not need to be a hospital. A could
just as well be Alice giving Dr. B a capability to do something on her
account. Dr. B's signature needs to be non-repudiable. Dr. B then has to
delegate their capability to some other entity. That delegated entity could
be B's employer that operates an information system that will actually
perform the transaction. Or, that delegate might be another staff member,
as colleague of Dr. B who then signs and becomes accountable.

- Adrian

**Comment by talltree** [comment]
I was assigned this issue but it's really @dhh1128 driving this. So I will ping him to follow up and decide next steps.

**Comment by dhh1128** [comment]
Thank you for the thoughtful response, @dlongley. Good stuff.

>So, you can create a verification method that expresses whatever constraints in it you'd like. However, this sort of information sounds like it belongs somewhere other than a DID Document. Ideally, it would be expressed somewhere that comes into contact with the system that performs the signing vs. the one that performs the verifying. Verification relationships help verifiers prevent proofs that have already been created from being misused for something other than their intended purpose. Here, it appears that you want to place specific restrictions on what you can actually sign -- and stop the proof from being created in the first place.

Yes. But your answer tells me we may have a different, fascinating misalignment. I don't think of the phrase "verification relationship" as having anything except coincidence in common with the role of "verifier" in the VC trust triangle. Apparently you do? ("Verification relationships help verifiers prevent proofs that have already been created..." seems to imply that. Why else would you assume proofs have already been created and that verification relationships can't be exercised during issuance?) If this misalignment actually exists, I need a different issue against DID core to clarify the definition.

>I would also shy away from these sorts of specifics in a DID Document just because of their tendency to reveal more information about a DID subject than may be desired. Some DID methods may be more naturally privacy preserving than others, but verification methods are meant to be DID method agnostic -- which may lead some to attempt to use them with DID methods where they may be harmful. Ideally, DID method designers will place their own restrictions to help prevent that sort of thing, but in the interest of avoiding such issues, my advice would be to put this sort of information elsewhere both for privacy purposes and because it seems to be related more to the specific message that is being signed than the general intent of a proof.

Deja vu from our conversation about service endpoints coming out for privacy reasons. :-) I am focused on two scenarios: peer DIDs, which don't have the privacy issue you're worried about, and public DIDs for institutions, which also don't have the privacy issue you're worried about. I don't disagree with your general concern, but I don't know how much to weight it, given that it's irrelevant to my particular frame. Pondering...

>I actually think this applies quite nicely (and I have used capabilities for almost exactly the same use case myself). If A exposes an endpoint for performing digital signatures, it can give B a capability to use that endpoint.

This doesn't satisfy my particular use case, because I don't want A to have to run a service to help B get its work done. But I agree that it works if that requirement is abandoned.

**Comment by dhh1128** [comment]
I am satisfied to close this issue. The pushback has given me some good thoughts. Not sure how I'll solve the problem, but I'll probably use some of the suggestions above.

I implicitly asked @dlongley a question about the definition of "verification relationships" in my comment above; I'll leave the ticket open for a day or two in case he wants to respond about that. However, the WG can close my issue otherwise as it sees fit.

**Comment by dlongley** [comment]
> ("Verification relationships help verifiers prevent proofs that have already been created..." seems to imply that. Why else would you assume proofs have already been created and that verification relationships can't be exercised during issuance?

"verifiers" there simply refers to verifiers of "proofs", it isn't VC-specific. You can certainly use verification relationships "during issuance" -- you can do whatever you want. But the main reason for expressing verification relationships is for verifiers (of proofs) to make use of them.

**Comment by msporny** [comment]
Looks like the original issue submitter is ok with closing the issue and his last request for a response about "verification relationships" was granted. Closing in 7 days unless there are objections.

**Comment by dhh1128** [comment]
Confirming that I am okay to close.

**Comment by kdenhartog** [comment]
Closing after 8 days pending with author of issuing saying its ok to do so.
