### ISSUE TITLE
Some comments by Steven Rowat

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#48]
@peacekeeper moved from CCG (https://github.com/w3c-ccg/did-spec/issues/267)

**Comment by rhiaro** [comment]
Everything in the original issue is addressed except for:

> In Section “5.10 Extensibility”:
>
> — Uses “we" and "us”; again different from the rest of the document.
> — Less terse writing than the rest of the document to this point; more like a marketing section; ie., uses what appear to be strictly unnecessary phrases like “a simple matter of” and “developers are urged to”.
>
> I believe it would be more in keeping with the rest if this section was rewritten slightly more tightly, and fully passive voice.

I agree with the comment, and think that the extensibility section reads like something that should be in an implementation guide rather than the spec. But I suspect there is history around that section originally getting written, and also note that it is very similar to the equivalent section in the VC spec.

I volunteer to rewrite that section "more tightly" if there is agreement that this is the right thing to do.

**Comment by msporny** [comment]
Changes were made, questions were asked of original commenter, no response, WG has moved on and is rewriting many of the extensibility sections, closing.
