### ISSUE TITLE
The definition of "the top-level" of the abstract data model is unclear 

### ISSUE THREAD

**Issue by shigeya** [w3c/did-core#505]
There are several places using the expression "the top level of DID Document" or alike. 

The "top-level" of "abstract data model", without defining the structure seems unclear.

I think we assumed the abstract data model has a hierarchical structure.
I propose to mention it in the definition of DID documents.

**Comment by msporny** [comment]
Committed 6434f17 to unify the language around "top level", "highest level", and "top-most" to just use "topmost" everywhere.

**Comment by msporny** [comment]
I believe this is addressed now, closing. Please re-open if you disagree @shigeya.

**Comment by shigeya** [comment]
> I believe this is addressed now, closing. Please re-open if you disagree @shigeya.

looks good to me.

**Comment by TallTed** [comment]
@msporny

Direct commits should be avoided as much as possible.

They don't offer a way to ignore white-space changes during review, nor to make suggestions before merge... and making a PR to adjust a tiny piece of a direct commit is a much heavier lift since it's a PR against the whole document(s) involved in that direct commit.

Also, comments made on that commit don't have the same impact as comments or change suggestions on a PR, e.g., https://github.com/w3c/did-core/commit/24b049f45284d852e2da6796c96de87abcf94ef9#r45310176 from @shigeya, which doesn't appear to have been acted on nor responded to.

**Comment by msporny** [comment]
@TallTed wrote:
> Direct commits should be avoided as much as possible.

Yes, agreed. The only time I do them is to address fairly straight forward editorial issues/changes (like this one), everything else that needs feedback goes through a PR.

> Also, comments made on that commit don't have the same impact as comments or change suggestions on a PR

As a general rule, people shouldn't comment on commits as no one is notified of those, AFAIK... but I can't fix Github's interface.

**Comment by shigeya** [comment]
> As a general rule, people shouldn't comment on commits as no one is notified of those, AFAIK... but I can't fix Github's interface.

I didn't know the general rule. Now I understand that.. ok. will not use comment on commits.

**Comment by TallTed** [comment]
> people shouldn't comment on commits as no one is notified of those, AFAIK

omg, really?  I've left a bunch in recent years...  I wonder if there's a way to query github for them, so I can review and re-address whatever issues those were‽
