### ISSUE TITLE
[Convention] Method `0` (zero) become a well-known method for retrieving properties/metadata from/about a particular DID Server

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#51]
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/271)

**Comment by peacekeeper** [comment]
I am opposed to this, since:
- This feels like abusing the concept of a "DID method" for something that should be done another way.
- This would not satisfy the requirements of a DID method, e.g. the operations Create/Read/Update/Deactivate would be meaningless.
- Retrieving properties/metadata from a DID resolver (I assume that is meant by "DID Server" in the PR title) should be done in other ways, e.g. by additional function calls or APIs that are separate from DID resolution itself.

Note several similar discussions: https://github.com/w3c-ccg/did-resolution/issues/26, https://github.com/w3c-ccg/did-spec/issues/171, https://github.com/w3c-ccg/did-spec/issues/171#issuecomment-465750325, https://github.com/w3c-ccg/did-spec/issues/167#issuecomment-462421237

**Comment by msporny** [comment]
I agree with all of @peacekeeper's points. Suggest we close this issue with no changes to the spec.

**Comment by jandrieu** [comment]
+1 to closing. This is a resolver meta-functionality issue and not core to how DIDs and DID Documents enable secure interactions with a subject.

**Comment by mwherman2000** [comment]
+1 to closing.  I'm doing this a different way (now).

**Comment by msporny** [comment]
> +1 to closing. I'm doing this a different way (now).

Great, thanks for the response @mwherman2000 - closing.
