### ISSUE TITLE
Global uniqueness of method-specific-id is not necessary, also hard to achieve

### ISSUE THREAD

**Issue by shigeya** [w3c/did-core#575]
In 7.1 Method Schemes,

> The method-specific-id value SHOULD be globally unique by itself. Any DID generated by the method MUST be globally unique.

Global uniqueness of DID is necessary. But:

- The definition of global uniqueness of method-specific-id is unclear.
- There is no easy way to guarantee the uniqueness of method-specific-id among methods.

Thus, the word `globally` should be removed, and also need to say it's unique within a method, thus I propose:

> The method-specific-id value SHOULD be unique within a method. Any DID generated by the method MUST be globally unique.

or just eliminating the first sentence seems fine:

> Any DID generated by the method MUST be globally unique.

**Comment by shigeya** [comment]
Applied 1st option. Also, changed to use MUST to align with the following sentence.

**Comment by peacekeeper** [comment]
I believe the background of this sentence is that in the early days of DIDs, there were some ideas that a DID could be created independently of a specific DID method, and that the same identifier could exist within different DID methods and must therefore be globally unique. This kind of thinking is now coming back in some form in KERI.

But today's design of DIDs leaves the use of the method-specific-id completely up to the DID method. Therefore I agree with you that defining or guaranteeing global uniqueness of the method-specific-id is difficult or impossible.

I guess in order to not completely abandon the original thinking here, we could change the SHOULD to MAY (or might). For some subsets of DID methods, the statement about global uniqueness of the method-specific-id is still true.

**Comment by shigeya** [comment]
@peacekeeper I made a change to PR #579. Would you please review it? I've resurrected the definition with the word 'globally', change the line to use `might`.

**Comment by peacekeeper** [comment]
@shigeya looks great, thanks!

**Comment by peacekeeper** [comment]
@shigeya can we close this now that https://github.com/w3c/did-core/pull/579 has been merged?

**Comment by shigeya** [comment]
@peacekeeper I was thinking of asking a question in the Special Topic Call. I was not sure somebody other than the editors may close the issue. Closing now.
