### ISSUE TITLE
alsoKnownAs at risk?

### ISSUE THREAD

**Issue by rhiaro** [w3c/did-core#584]
Given the (appropriate) trend of removing as much as possible from the Core Properties, I question whether `alsoKnownAs` belongs there. It seems high risk of inviting PII, especially as it is not restricted to DIDs (but any URIs). I'd like to know about who is planning to implement this and what for? Should we mark it as at risk (of being moved to the Registries)?

**Comment by msporny** [comment]
I agree, given the current trajectory of consensus in the WG wrt. moving away from placing anything that could be PII in the DID Document (as a part of DID Core). I expect that @jandrieu will scrutinize this particular feature. @csuwildcat and @talltree may also want to weigh in here.

**Comment by msporny** [comment]
Reassigning to @rhiaro who volunteered to add a speculative PR wrt. this issue.

**Comment by msporny** [comment]
PR #589 has been raised to address this issue. This issue will be closed when that PR is merged.

**Comment by csuwildcat** [comment]
This one is less an issue for me, because yes, it's more likely to be a PII vector, and your AKA assertions can be done via something like a personal datastore that exposes AKA statements. This is in contrast to the deterministic equivalence properties, which are PII vectors and can't be done by anything but a Method's secure resolution process. For this reason, I'm indifferent about AKA.

**Comment by msporny** [comment]
PR #589 has been merged, which marks alsoKnownAs as at risk... closing.
