### ISSUE TITLE
Minor editorial fixes for Architecture Diagrams

### ISSUE THREAD

**Issue by shigeya** [w3c/did-core#618]
I found some text that needs editorial fixes:

- [x] `DID dereferencer` -> `DID URL dereferencer`
- [x] `DID Document` -> `DID document`

Since we will apply editorial fixes to the text, which may require editorial fixies to diagrams, I will fix the diagrams after editorial fixes are settled.

**Comment by peacekeeper** [comment]
@shigeya regarding your first item, I created PR https://github.com/w3c/did-core/pull/624, does this fix that first item?

Regarding your second item, I think fixing capitalization of terms will probably happen as one of the last steps in the spec finalization process. Lower-case "DID document" is correct. I think you could fix your diagram without necessarily waiting for the spec text to be fixed in this case? But up to you of course.

**Comment by shigeya** [comment]
@peacekeeper on the first item,  I've not realized the difference in the spec text. I meant *in the diagram* ,  So please merge PR#624.

For the second item, it's only about diagrams too. I will create a PR for it, after thinking about how I will work on extra figures.

In general, we will see some changes in the main spec text. From my point of view, don't know the editors' decisions yet, thus, I thought it's a good idea to apply the change when I know the main spec text is settled (or close to settlement). But maybe, I better create Issues/PRs incrementally to make the number of changes needed to be visible at the issue level. Anyway, actually, I prefer incremental PR creation. thanks:D

**Comment by shigeya** [comment]
Fixed with PR #634.

**Comment by msporny** [comment]
PR #634 has been merged, closing.
