### ISSUE TITLE
Diagrams need SVG and detailed description

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-core#625]
As noted in some PRs (e.g. https://github.com/w3c/did-core/pull/595, https://github.com/w3c/did-core/pull/596, https://github.com/w3c/did-core/pull/597), diagrams should be in SVG format (preferably without converting characters into geometry), and have a detailed description (using "longdesc" or other appropriate feature). This issue is to make sure we go over all diagrams and check this.

Also see https://github.com/w3c/did-core/issues/118.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-03-30-did#section5-1) on 2021-03-30

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.1. Diagrams need SVG and detailed description 

_See github issue [#625](https://github.com/w3c/did-core/issues/625)._




**Markus Sabadello:** I created this issue when I was working on some of the diagrams for DID Core, especially those for the Data model and DID resolution section  
… I did not create SVG versions yet, which Ivan suggested and I agree with that  
… So I don't forget. I will do that for the ones I created. Not sure if there are other non-SVG diagrams  
… but if there are then we should also convert those  

**Brent Zundel:** Are you looking for assistance with that?  

**Markus Sabadello:** I will do it for the ones I created  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-05-04-did#section7-2) on 2021-05-04

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.2. Diagrams need SVG and detailed description 

_See github issue [#625](https://github.com/w3c/did-core/issues/625)._




**Brent Zundel:** I believe some work has gone into changing diagrams to SVG format. Or perhaps I am thinking of new diagrams that are SVG.  

> *Amy Guy:* brent, descriptions are also on my radar if nobody else gets there first

**Brent Zundel:** We need detailed descriptions for each diagram.  
… Pretend that you are telling the diagram to someone who can't see - since that what this is for.  
… The technical level to contribute is low.  
… Currently assigned to Markus.  

</details>

**Comment by peacekeeper** [comment]
Here are my source files, I have been struggling with converting them to SVG. They are used in sections [6.1](https://www.w3.org/TR/did-core/#production-and-consumption) and [7.1](https://www.w3.org/TR/did-core/#did-resolution) of the spec.

[For DID Core.odp](https://github.com/w3c/did-core/files/6542825/For.DID.Core.odp)

Can anyone help to convert them to SVG? I think @shigeya may have ideas on how to do this?

**Comment by shigeya** [comment]
After tried several options with applications on my Mac, I found that OpenOffice can export to SVG directly:)

<img width="428" alt="ScreenShot 2021-05-26 8 46 56" src="https://user-images.githubusercontent.com/69672/119582185-1e718b80-bdff-11eb-88ac-f44c5f4b2571.png">

I tested, and it works. At least, I can open the output with Safari.
[For.DID.Core.svg.zip](https://github.com/w3c/did-core/files/6543012/For.DID.Core.svg.zip)
(Since GitHub comments do not accept SVG, it's in ZIP)

You may need to adjust the exported SVG by using Diagrams.Net.
I changed all fonts to Helvetica family (as a conservative choice).

For the test, I suggest to open it in Chrome and FireFox to verify there are no strange overlaps.

As I remember, @rhiaro reported me that a version of SVG didn't display in her environment.
So she may help check the resulted SVG.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-05-25-did#section3-2) on 2021-05-25

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.2. Diagrams need SVG and detailed description 

_See github issue [#625](https://github.com/w3c/did-core/issues/625)._




**Manu Sporny:** using the GitHub change tool would help the most  

**Markus Sabadello:** I should have done this much sooner. So far I haven't been able to.  

> *Drummond Reed:* I did the diagrams with an OpenOffice app, but I can't get them converted to SVG.

> *Shigeya Suzuki:* Please let me know exportable formats, then I may help.

**Brent Zundel:** if folks can help, please offer  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-06-08-did#section5-4) on 2021-06-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.4. Diagrams need SVG and detailed description 

_See github issue [#625](https://github.com/w3c/did-core/issues/625)._




**Brent Zundel:** the diagrams need descriptions  

**Shigeya Suzuki:** markus asked me to help find a way to do the convert to svg  
… the tool he's using can be used to export to svg, should be no problem  
… once he has time to do that then done  

**Brent Zundel:** we'll have the svg  
… descriptions?  

**Shigeya Suzuki:** I think he will work on that  

**Brent Zundel:** we'll leave that to markus  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-06-15-did#section5-1) on 2021-06-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.1. Diagrams need SVG and detailed description 

_See github issue [#625](https://github.com/w3c/did-core/issues/625)._




**Brent Zundel:** issue 625  

**Markus Sabadello:** recommendation didn't work  

**Brent Zundel:** other aspect of this issue - anyone can jump in and contribute.  

> *Manu Sporny:* If it were me, I'd just recreate everything in Google Draw :)

**Ivan Herman:** might be able to import from open office into google doc  

**Charles Lehner:** also open to helping  

> *Drummond Reed:* Fantastic

</details>

**Comment by peacekeeper** [comment]
Need SVG versions:

- [ ] diagram-production-consumption.png
- [ ] diagram-resolve-resolverepresentation.png
- [ ] figure-a.1-did-and-did-document-graph.png
- [ ] figure-a.2-also-known-as-graph.png
- [ ] figure-b.1-controller-and-subject-equivalence.png
- [ ] figure-c.1-independent-did-controllers.png
- [ ] figure-c.2-group-did-controllers.png

Need to check detailed descriptions:

- [ ] parts-of-a-did.svg
- [ ] did_brief_architecture_overview.svg
- [ ] diagram-did-document-entries.svg
- [ ] diagram-production-consumption.png
- [ ] diagram-resolve-resolverepresentation.png
- [ ] did_url_dereference_overview.svg
- [ ] did_detailed_architecture_overview.svg
- [ ] figure-a.1-did-and-did-document-graph.png
- [ ] figure-a.2-also-known-as-graph.png
- [ ] figure-b.1-controller-and-subject-equivalence.png
- [ ] figure-c.1-independent-did-controllers.png
- [ ] figure-c.2-group-did-controllers.png

**Comment by peacekeeper** [comment]
@talltree it looks like you added 5 diagrams in PNG format for [Appendix C](https://www.w3.org/TR/did-core/#architectural-considerations) in https://github.com/w3c/did-core/commit/39877b1ec5699382e96d3e7f151dd43f5813e4fc.

Can you create SVG versions of those?

**Comment by peacekeeper** [comment]
https://github.com/w3c/did-core/pull/781 and https://github.com/w3c/did-core/pull/785 add detailed descriptions for the remaining diagrams. After those PRs are merged, all diagrams will have detailed descriptions. Assuming that we don't actually need SVG versions of all diagrams, I think we can then close this issue.

**Comment by peacekeeper** [comment]
https://github.com/w3c/did-core/pull/786 replaces the last remaining PNG diagrams with SVG versions.

**Comment by TallTed** [comment]
@peacekeeper -- Would you tick off [the relevant boxes](https://github.com/w3c/did-core/issues/625#issuecomment-861639733)?

**Comment by msporny** [comment]
> @peacekeeper -- Would you tick off [the relevant boxes](https://github.com/w3c/did-core/issues/625#issuecomment-861639733)?

Done, and we're done here.

PRs #786, #781, #785, #767, and #771 address this issue. The issue was raised by @peacekeeper and resolved by @clehner and @peacekeeper. Closing with explicit agreement that the issue has been resolved.
