### ISSUE TITLE
At risk: nextUpdate, nextVersionId

### ISSUE THREAD

**Issue by oed** [w3c/did-core#667]
I just noticed that `nextUpdate`and  `nextVersionId` was marked as "at risk" in https://github.com/w3c/did-core/pull/601

@msporny Can you please clarify why this was done? Imo this renders the DID spec completely unusable in hash linked data structures where you need to be able to verify when a particular key was revoked. The full issue is described here: https://github.com/w3c/did-core/issues/483

> The DID Working Group is seeking implementer feedback on this feature. If there is not enough implementation experience with this feature at the end of the Candidate Recommendation period, it will be removed from the specification. 

What exactly are you looking for here?

**Comment by msporny** [comment]
> @msporny Can you please clarify why this was done?

This is an EDITORIAL warning. It's basically saying -- "These features were added late in the game (which they were), the WG is unsure if we'll have enough implementations of the feature (which is true), and if we don't, we'll take it out of the specification (which is standard practice). That doesn't mean the features will never exist... the fallback position is that you'll have to define it and register it in DID Specification Registries -- which can be done with less than two days of work.

For features to remain in the specification during the Candidate Recommendation phase, the WG requires: 1) volunteers to write tests for the feature, and 2) at least two independent implementers to implement the feature.

We know that many of the other features in the specification already have volunteers to write tests and at least two independent implementations, which is why they're not marked as at risk. A number of people in the WG see the value of nextUpdate and nextVersionId... but until we see those actually implemented in real DID Resolvers, the jury is still out wrt. people prioritizing the implementation of those features over other ones.

Does that answer your question, @oed?

**Comment by oed** [comment]
That makes sense. Thanks for clarifying @msporny! 

I'll happily volunteer to write tests for this feature. Where do these usually reside and what format do they take? 

I will also commit to provide one of the independent implementations 👍

**Comment by msporny** [comment]
> I'll happily volunteer to write tests for this feature. I will also commit to provide one of the independent implementations

That is exactly the right way to respond to a feature at risk! :)

> Where do these usually reside and what format do they take?

The tests will be in the DID Test Suite: https://github.com/w3c/did-test-suite/

Instructions on contributing are here: https://github.com/w3c/did-test-suite/#getting-started

@OR13 is in charge of the DID Test Suite and might be able to help you out wrt. getting started. We are currently doing the final pass on the machine-testable feature requirements in the specification and hope to have the final list by the end of this week. I don't expect the requirements around nextUpdate and nextVersionId to change, so you could probably safely submit tests for that now -- @OR13 could give you more instruction on that.

With that, can we mark this issue as resolved, @oed -- future issues wrt. testing should be raised in https://github.com/w3c/did-test-suite/

**Comment by oed** [comment]
> With that, can we mark this issue as resolved?

Fair enough. Before that I just would like to know if there is some sort of deadline that shouldn't be missed if this feature is not to be removed?

**Comment by msporny** [comment]
> Fair enough. Before that I just would like to know if there is some sort of deadline that shouldn't be missed if this feature is not to be removed?

The deadline is "the end of the W3C Candidate Recommendation Phase". The first round of CR is expected to end at the end of April -- there should be tests and two independent implementations at that point... so you have ~2.5 months to get it done.

**Comment by msporny** [comment]
Initial question asked by @oed has been answered with a clear path forward. Closing.
