### ISSUE TITLE
(Editorial) acknowledgement at the right place

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#669]
(I deliberately have not made a PR of this yet, checking whether there is any agreement on this): it is customary for specifications to have a separate 'Acknowledgement' section towards the end of the document, usually as an appendix. It is also customary to list either the full list of WG members or the active members of the WG. This section does not exist yet.

If such section exists, I would propose the acknowledgements to the RWOT community, as well as to the CCG, to be moved from the status section to that separate acknowledgement section. I do not think the current place is the right one.

(If there is an agreement over this, I am happy to submit a PR. Note that I also have a script that is capable of extract the full list of WG participants and dump that into an acknowledgement file.)

**Comment by msporny** [comment]
> it is customary for specifications to have a separate 'Acknowledgement' section towards the end of the document, usually as an appendix. It is also customary to list either the full list of WG members or the active members of the WG. This section does not exist yet.

Yes, agreed, and we will create this section right before we go into PR. I also agree that we should move acknowledgements in SoTD to that section.

I would like to wait because I typically have scripts that I run to create the acknowlegements sections. The scripts download and scan every issue, every PR, every mailing list conversation across did-wg and ccg, contributors to papers at RWoT, etc. In other words, it attempts to do a full acknowledgement of all the people that contributed to the work, even if they weren't in the WG. Only about half of the work that went into the DID spec was done in the DID WG... the other half was done at RWoT, IIW, CCG, etc.

So, if we can, let's hold off on this until right before PR.

**Comment by iherman** [comment]
That is fine with me.

**Comment by iherman** [comment]
There is now a PR for this (#704). This issue can be closed if and when #704 is merged.

**Comment by msporny** [comment]
PR #704 has been merged, closing.
