### ISSUE TITLE
FAQ Question: Can the DID Controller of a DID Document be updated/changed after the DID Document has been registered?

### ISSUE THREAD

**Issue by mwherman2000** [w3c/did-core#719]
New FAQ Question for the https://w3c.github.io/did-core/#frequently-asked-questions-about-did-identification section:

Can the DID Controller of a DID Document be updated/changed after the DID Document has been registered?

I presume yes?

**Comment by msporny** [comment]
Yes, it can.

**Comment by OR13** [comment]
We describe wallet caching for offline use cases here: https://w3c-ccg.github.io/universal-wallet-interop-spec/#DIDResolutionResponse

I think generally there should be some warnings about caching and trusting network enabled resolvers.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-03-30-did#section5-7) on 2021-03-30

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.7. FAQ Question: Can the DID Controller of a DID Document be updated/changed after the DID Document has been registered? 

_See github issue [#719](https://github.com/w3c/did-core/issues/719)._




**Brent Zundel:** Currently unassigned, and has one comment.  
… I don't know that more needs to happen  

**Manu Sporny:** There is a request to add a FAQ for it.  
… drummond, are you refactoring the end of the document to be a FAQ?  

**Drummond Reed:** I thought the goal was to refactor it to not be a FAQ  

**Manu Sporny:** My bad, the other way then  
… Never mind  
… I was going to say... can you speak to it ...  

**Drummond Reed:** Definitely. Feels like one of the things to discuss  
… If you want me to cover it, I'm happy to do that  
… All the update will do is change the questions into headings. It wasn't a FAQ originally ...  
… I'll take that action item.  

</details>

**Comment by msporny** [comment]
@talltree ping on this issue, can you write a PR to address it?

**Comment by talltree** [comment]
Yes, working on it.

**Comment by msporny** [comment]
PR #754 has been raised to address this issue. This issue will be closed once that PR has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-05-25-did#section3-4) on 2021-05-25

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.4. FAQ Question: Can the DID Controller of a DID Document be updated/changed after the DID Document has been registered? (issue did-core#719)

_See github issue [#719](https://github.com/w3c/did-core/issues/719)._




> *Brent Zundel:* PR that addresses this: [https://github.com/w3c/did-core/pull/754](https://github.com/w3c/did-core/pull/754)

</details>

**Comment by msporny** [comment]
PR #754 has been merged.

@mwherman2000 can you please confirm that the PR addressed your issue?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-06-08-did#section5-5) on 2021-06-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.5. FAQ Question: Can the DID Controller of a DID Document be updated/changed after the DID Document has been registered? 

_See github issue [#719](https://github.com/w3c/did-core/issues/719)._




**Brent Zundel:** assigned to drummond  

**Drummond Reed:** I've accepted all the suggestions and that's ready to merge  

**Manu Sporny:** it's been merged, waiting on michael to confirm we addressed the issue and we can close it with explicit confirmation  

**Brent Zundel:** that's all of the issues  
… six PRs  

**Manu Sporny:** we should discuss one  
… 741  

</details>

**Comment by msporny** [comment]
Trying again...

PR #754 has been merged.

@mwherman2000 can you please confirm that the PR addressed your issue? We will close this issue in 7 days if we don't hear from you before then.

**Comment by msporny** [comment]
Issue submitter has been non-responsive. WG took action to address the issue by creating and merging a PR that speaks directly to the issue. Closing with implict assumption that the submitter's issue has been addressed.

**Comment by mwherman2000** [comment]
Looks good.  Trying to plow through my backlog of 3000 Github notifications :-)
