### ISSUE TITLE
All appendix sections needs to be cleaned up.

### ISSUE THREAD

**Issue by msporny** [w3c/did-core#728]
The appendices in the document need one last Editorial clean up pass before we exit CR. This issue is just here to track that task.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-06-08-did#section5-2) on 2021-06-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.2. All appendix sections needs to be cleaned up 

_See github issue [#728](https://github.com/w3c/did-core/issues/728)._




**Brent Zundel:** next 728  

**Manu Sporny:** there are 4 remaining PRs, once those are merged all of the appendices will have had all the editorial changes  
… means we're done with editorial work  
… modulo small adjustments  

**Brent Zundel:** good news  
… next is 729  

</details>

**Comment by msporny** [comment]
This is finally done, all PRs to clean up the appendixes have been merged. Closing.
