### ISSUE TITLE
Examples might be out of date

### ISSUE THREAD

**Issue by msporny** [w3c/did-core#734]
The following section might be out of date (and contains no prose explaining the examples): 

https://w3c.github.io/did-core/#examples 

We need to: 

1. Make sure the examples are correct.
2. Write some prose to explain each example.
3. Consider moving the examples to the implementation guide so that they can be updated more frequently (and then point to the implementation guide for those interested in examples.

If these items above are not done, we should move the entire appendix to the implementation guide.

@OR13, since you wrote this section, can you make a pass on it to make sure it's correct (as it'll probably be at least 6-12 months before we get a chance to fix it again once the REC is out).

**Comment by OR13** [comment]
yes, examples are certainly out of date, we probably need w3id.org/security/suite/.... everywhere.

**Comment by OR13** [comment]
@msporny looks like you got to many if not all of these.

**Comment by msporny** [comment]
> @msporny looks like you got to many if not all of these.

I think the only ones I touched were the multibase ones... didn't touch many of the others. I wouldn't assume I got them, I was purely focusing on publicKeyMultibase when I did my pass (which I'm not sure was correct). At the very least, need a second set of eyes on the examples.

**Comment by OR13** [comment]
cool, I can see a few missing from this example:

https://w3c.github.io/did-core/#example-31-did-document-with-many-different-verification-methods

which IMO is really an anti pattern example...

I will open a PR to clean it up.

**Comment by OR13** [comment]
PR is up for this: https://github.com/w3c/did-core/pull/748

**Comment by msporny** [comment]
PR #748 has been raised to address this issue. This issue will be closed once that PR has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-05-25-did#section3-5) on 2021-05-25

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.5. Examples might be out of date 

_See github issue [#734](https://github.com/w3c/did-core/issues/734)._




_See github pull request [#748](https://github.com/w3c/did-core/pull/748)._




**Drummond Reed:** I submitted PRs on that and the next issue; they just need review  

**Orie Steele:** I removed the Ethereum address example  
… there is still a potential issue with having a public key multibase example first  
… so I hoped that providing several examples would solve the problem  

**Brent Zundel:** a link to the PR is in IRC so please review  

</details>

**Comment by msporny** [comment]
PR #748 has been merged and addressed my concerns.
