### ISSUE TITLE
Add link to DID use cases document.

### ISSUE THREAD

**Issue by msporny** [w3c/did-core#766]
We still don't have a link to the use cases document. As @philarcher has mentioned on numerous occasions, it might be a good idea to put that in the spec. :P

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-06-15-did#section5-3) on 2021-06-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.3. Add link to DID use cases document 

_See github issue [#766](https://github.com/w3c/did-core/issues/766)._




**Brent Zundel:** 766 add link to DID use-cases document  

**Manu Sporny:** Phil reminded me this morning - I have failed to put a link into it. will do it.  

</details>

**Comment by msporny** [comment]
PR #774 has been raised to address this issue. This issue will be closed once that PR is merged.

**Comment by msporny** [comment]
PR #774 has been merged with @philarcher agreeing that the issue is resolved in that PR. Closing.
