### ISSUE TITLE
Leverage RFC7518 to specify cryptographic algorithms

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#8]
@AxelNennker moved from CCG (https://github.com/w3c-ccg/did-spec/issues/38)

**Comment by selfissued** [comment]
I agree that we should use algorithm identifiers from the IANA "JSON Web Signature and Encryption Algorithms" registry at https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms.  And when new algorithm identifiers are needed, we should proactively register the additional ones needed.  Note that only a public specification is needed to do this - not an RFC.

**Comment by msporny** [comment]
The DID spec doesn't specify things at the RFC7518 level... but the cryptographic suites do, and yes, they should reference RFC7518 when possible.

That said, there is nothing for us to do w/ the spec currently. If the spec starts doing things at the RFC7518 level, then we should reconsider. Closing unless there are objections in the next 7 days.

**Comment by selfissued** [comment]
The spec needs to specify things at this level if we're to achieve interop.  I object to closing this issue.

Note this may also be related to https://github.com/w3c/did-core/issues/169.

**Comment by msporny** [comment]
> The spec needs to specify things at this level if we're to achieve interop. I object to closing this issue.

Ok, then this will need to be discussed in the group. We had previously (at the 2019 DID WG meeting at W3C TPAC) agreed that we were not going to put normative statements like this into the specification as how a DID Document is secured was out of scope. It sounds like you're now wanting to revisit that decision.

**Comment by burnburn** [comment]
Chairs will schedule a call to discuss.

**Comment by selfissued** [comment]
Per #169, while we should embrace use of pertinent external registries, such as those administered by IANA, any normative definitions not in stable documents, such as W3C Recommendations, IETF RFCs, or IANA registries, so that the whole of what is needed by implementers is either in stable references or in this specification.

**Comment by selfissued** [comment]
JWK key representations can include an "alg" value specifying use of an algorithm from the IANA JSON Web Signature and Encryption Algorithms registry.

**Comment by selfissued** [comment]
I would suggest that at least some the JWK Examples requested in #171 include an "alg" field.

**Comment by OR13** [comment]
You need an external description if its not a JWK... so adding a property that only works for JWK does not help.

**Comment by OR13** [comment]
and JWK can have arbitrary JSON... so in general, it's not enforceable.

**Comment by msporny** [comment]
I'm suggesting that this issue has been overtaken by events. Yes, we use JWA *and* we use the Linked Data Security stuff to specify algorithms... so we use both. What action needs to be taken? If there is no action, then there is nothing to do, and we should close this issue.

**Comment by OR13** [comment]
but if specifying `alg` is a best practice... I suppose we could add support for that here: https://github.com/w3c-ccg/lds-jws2020

The reason we didn't do this, is that a best algorithm is knowable from the `kty` and `crv`... in other words, we didn't like the idea of allowing people to specifically request old md5 / rsa crypto that is not safe....

technically, you can use a base58 encoded public key, convert it to JWK, and guess that ES256K should be used... because thats literally the only registered `alg` for `secp256k1`... for RSA keys, its a little harder.... but for NIST curves, there are similarly only 1 choice... so I'm not sure we would be doing much other than increasing attack surface by adding `alg` to JWKs... because you can do that right now... they are of type `@json`... which means arbitrary JSON is supported.

If we want to restrict JWKs further, and add a requirement that if `publicKeyJwk` is used then it MUST have an `alg` field.... I suppose we could do that.

**Comment by OR13** [comment]
Related Issues:

https://github.com/decentralized-identity/didcomm-messaging/pull/52
https://github.com/w3c-ccg/lds-jws2020/issues/12

I think the same concern applies for JWE as JWA... in other words... does DID Core make recommendations regarding expressing support for JWA and JWE inside a `publicKeyJwk`... or does it rely on the suite to make that recommendation.

**Comment by OR13** [comment]
I think its related to the special call, we do recommend algorithms for jose like so: https://github.com/w3c-ccg/lds-jws2020#supported-jose-algorithms to be discussed on the call.

**Comment by OR13** [comment]
We don't need to rely on RFC7518, we need to rely on suite authors to define the relationship between suite "type" and external registries. DID Core does not require us to import a registry.

**Comment by OR13** [comment]
@msporny noted on call... the discussion we had on the special topic call, and naming... the group said the job was someone else job... we are discussing naming, and what those specs say... we believe thats outside the scope of the DID WG... its up to the crypto suites to link to JWK, and we are doing that elsewhere....the group has decided that this is (now) not in our purview... and i think it will result in what you want, and some suites will refer to...

**Comment by selfissued** [comment]
To the extent that we have PublicKeyJwk key representations, we should include algorithms registered in the IANA JOSE Algorithms registry as "alg" values in the JWKs.

**Comment by OR13** [comment]
why, JWK alg values are registered here: https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms

suites that support them are responsible for saying so.... 
DID Core does not define suite, and per our last special topic call, has no opinion regarding their names....

Case in point: 

- https://github.com/w3c-ccg/lds-jws2020#supported-jose-algorithms=
- https://w3c-ccg.github.io/ldp-bbs2020/

**Comment by selfissued** [comment]
DID Core doesn't define crypto suites but does define key representations, which use crypto suites.

**Comment by OR13** [comment]
@selfissued  DID Core does not define JWK, which links those 2 things in one way, how they are linked in other ways would require controlling those suites... In the last special topic call, you and @jricher  made it clear you did not care how that linkage was defined for Linked Data. 

I wish we could have done that work here, because there are opinions about binding of the linkage between the concept of `kty` / `crv` and `alg`.... 

For example, I prefer to not bind the"verification method type" to the "signature type"... I like the style of JWK / JWS.

However, others don't agree, they prefer something that looks more like this:

`EcdsaSecp256k1VerificationKey2019` + `EcdsaSecp256k1Signature2019`
`SchnorrSecp256k1VerificationKey2019` + `SchnorrSecp256k1Signature2019`

vs

`JsonWebKey2020` => ['EcdsaSecp256k1Signature2019', 'SchnorrSecp256k1Signature2019', 'JsonWebSignature2020']

**Comment by selfissued** [comment]
@OR13 - this is the second time that you've asserted that @jricher and I don't care about naming, where at least for me, that is far from true.  There must have been some misunderstanding on the special topic call that you're referring to.  We should try to get to the bottom of it and correct it.

I would certainly prefer that we go with the simpler algorithm naming scheme that you cite:
> `JsonWebKey2020` => [`EcdsaSecp256k1Signature2019`, `SchnorrSecp256k1Signature2019`, `JsonWebSignature2020`]
What do we need to do to accomplish that?

Finally, I'll assert that issue #169 pertains to the set of decisions you're referring to.  We want the DID WG to be in control of its own destiny in terms of the names used in DIDs.  DIDs and DID methods should not need to refer to registries administered by community groups to have complete solutions.

**Comment by selfissued** [comment]
I spoke with @OR13 about the details of this and I now believe that since we have `JsonWebKey2020` registered in the DID Core Registries, that de-facto means that people can use algorithms from the IANA JSON Web Signature and Encryption Algorithms registry https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms with DIDs, which was the point of this issue.

I'm willing to declare victory and close this issue on that basis.  Thanks all for the good discussion.

**Comment by brentzundel** [comment]
No comments since marked pending close, closing.
