### ISSUE TITLE
Define conformance classes such as "DID document processor"

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-core#80]
We should have a section that defines what is a "conforming DID document processor", "conforming DID document", etc. Those conformance classes would obviously require compliance with all normative statements in the specification, but also talk about producing errors, and about any other required behavior in certain situations.

This came up in https://github.com/w3c/did-spec/pull/66#discussion_r335776271

**Comment by rhiaro** [comment]
Can we outline what the conformance classes would be? Then we can start working up spec text. I'm jotting down some thoughts.

Speaking very generally, the rule of thumb for interop when there are multiple alternate options is that:

* *producers* output their preferred.
* *consumers* MUST accept all possibilities.

'Producer' and 'consumer' terminology gets ambiguous because of the layers involved. In particular, a DID registry (previously known as a target system, eg. a distributed ledger, a filesystem, a database) could be considered both a producer of a DID document (in that it can serve one up) and a consumer (in that it has an interface for having one written to it) *but* I think we **do not** actually want to impose conformance constraints on any DID registries, at least *not in the core spec*. This is for DID method specs, if anywhere.

So conformance classes in the core spec could be:

* DID document processor (software that reads and parses a DID document)
* DID document producer (software that generates and serializes a DID document)

A DID Resolver would be both a DID document processor *and* a DID document producer.

Conformance criteria for a particular DID Registry would be defined by the relevant DID method specification. That is, it is out of scope for this specification to make normative statements about: how a DID registry internally stores its representation of the DID document; how the Registry interface is exposed for reading from or writing to. Thus, a DID registry is *not* considered a DID document processor nor a DID document producer for the purposes of did-core.

I don't see 'DID document' as a conformance class because the idea of a 'conformant DID document' is redundant, and my understanding of conformance classes is so that you can say your piece of software is doing one set of things or another (or both).
