### ISSUE TITLE
Controller confusion

### ISSUE THREAD

**Issue by mwherman2000** [w3c/did-core#819]
In https://www.w3.org/TR/did-core/#verification-method-properties, it says that `controller` is _required_. Clicking on `controller` in this table links to https://www.w3.org/TR/did-core/#did-controller ...which says _controller_ is _optional_.  These need to be differentiated or, at least, unlinked from one another.

**Comment by kdenhartog** [comment]
The controller property defined in https://www.w3.org/TR/did-core/#did-controller is for establishing the controller of the DID Document. The `controller` property defined in https://www.w3.org/TR/did-core/#verification-method-properties is about the controller of the verification method. They're two separate properties which follow different semantics because they're located in different objects of the JSON.

**Comment by TallTed** [comment]
The link from the `controller` in the [Verification Method Properties](https://www.w3.org/TR/did-core/#verification-method-properties) table does need to change, from https://www.w3.org/TR/did-core/#dfn-controller (not from https://www.w3.org/TR/did-core/#did-controller as @mwherman2000 said, though `did-controller` is the fragment ID of the section header for the section which contains the `dfn-controller` fragment).

The current target of the link is within [§ 5.1.2 DID Controller](https://www.w3.org/TR/did-core/#did-controller)

The correct target of the link is within [§ 5.2 Verification Methods](https://www.w3.org/TR/did-core/#verification-methods) -- but [this definition](https://www.w3.org/TR/did-core/#:~:text=DID%2DSPEC%2DREGISTRIES%5D.-,controller,-The%20value%20of) does not now have a unique fragment identifier in the HTML.

**Comment by msporny** [comment]
PR #820 has been merged to address this issue.
