### ISSUE TITLE
Context URL in spec examples is a 404

### ISSUE THREAD

**Issue by wip-abramson** [w3c/did-core#862]
The context URL - https://www.w3.org/ns/did/v1 - is used 17 times in the spec examples

However, it is returning a 404 error when I visit that URL.

**Comment by iherman** [comment]
Oops. I found the bug, and it should be working now.

Let me also write down what the bug was, because there is a lesson to be learned from it.

In this specific case, the HTTP hops for the context file were:

ns/did/v1 --> ns/did-vocab/v1 --> https://w3c.github.io/did-spec-registries/vocabs/v1/context.jsonld

but as did-spec-registries was recently renamed to did-extensions, that last URL went 404. I took therefore the liberty to change the redirection in the did-vocab/.htaccess file and things are working now. I hope that is fine.

There is a lesson to be learned, though. If one changes a GitHub repository's name, an automatic redirection is indeed set up for the repository URL itself. But that redirection _**does not happen for the w3c.github.io URLs**_. That may mean that several URLs that we use suddenly go 404. We should therefore try NOT to do such renaming lightly.

Another question is whether we should not put such "frozen" files into W3C date space and avoid relying on github.io for long term references. But that is another issue...

cc @msporny @pchampin

**Comment by msporny** [comment]
This has been fixed, the https://www.w3.org/ns/did/v1 URL is now returning the correct document.

**Comment by pchampin** [comment]
This was discussed during the [did meeting on 10 October 2024](https://www.w3.org/2024/10/10-did-minutes.html#584b).

<details><summary><i>View the transcript</i></summary>

<h3>DID Core Issue/PR Processing</h3>
<p><cite>burn:</cite> ok. Excellent. Manu, you have a pending close issue</p>
<p><cite>burn:</cite> issue 862.</p>
<p><cite>&lt;burn&gt;</cite> <a href="https://github.com/w3c/did-core/issues/862" rel="noopener noreferrer">w3c/<wbr>did-core#862</a></p>
<p><cite>manu:</cite> it's working. This is fixed.<br>
<span>… so we can close</span></p>
<p><cite>manu:</cite> any objections to closing?</p>
<p>[room is silent]</p>

<hr /></details>
